### ISSUE TITLE
图片问题

### ISSUE THREAD

**Issue by losewinner** [PeiandHao/Simple_OS_For_Studing#4]
您好，我想问一下，这里的图片好像都破损了，报了参数问题的错误，请问您图片还有备份吗

**Comment by peiwithhao** [comment]
有可能是百度那个图床挂了，我明天找找看

**Comment by peiwithhao** [comment]
太难崩了，里面的图片当时该就放在github的，现在没备份了 :(,同学如果感兴趣可以参考书籍<<操作系统真象还原>>，关于特定结构体的一些图片都在里面可以看到

**Comment by losewinner** [comment]
好嘞谢谢您了，我去看看那本书
